"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

# format = "$directory$os$git_branch$git_status$nodejs$rust$golang$php$character"
format = """
$os$directory$git_branch$git_status$nodejs$rust$golang$php$cmd_duration
$character"""

# Configure the command duration module
[cmd_duration]
min_time = 2_000        # Only show if the command takes 2 seconds or longer
format = "took [$duration](bold yellow) "

[os]
disabled = false
format = "[$symbol]($style) "
style  = "bold blue"

[os.symbols]
# Arch = ""
# Fedora = ""

[directory]
format            = "[$path](cyan) "
truncation_length = 4
truncate_to_repo  = true

[git_branch]
symbol = ""
format = "[$symbol $branch](bold purple) "

[git_status]
format     = "($ahead_behind$staged$modified$untracked$deleted$conflicted)"
ahead      = "[⇡$count ](bold cyan)"
behind     = "[⇣$count ](bold cyan)"
diverged   = "[⇡$ahead_count⇣$behind_count ](bold cyan)"
staged     = "[+$count ](bold green)"
modified   = "[●$count ](bold yellow)"
untracked  = "[?$count ](bold white)"
deleted    = "[✘$count ](bold red)"
conflicted = "[⚡$count ](bold red)"

[nodejs]
symbol = ""
format = "[$symbol $version](green) "

[rust]
symbol = ""
format = "[$symbol $version](red) "

[golang]
symbol = ""
format = "[$symbol $version](cyan) "

[php]
symbol = ""
format = "[$symbol $version](purple) "

[character]
format = "$symbol "
# success_symbol = "[➜](bold green) "
# error_symbol = "[➜](bold red) "
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_visual_symbol = "[❮](bold yellow)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_replace_one_symbol = "[❮](bold purple)"
disabled = false
